# Generated by Django 4.2.11 on 2026-09-11 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('color', models.CharField(blank=True, default='#00E5FF', max_length=7)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('archivado', 'archivado')], default='activo', max_length=20)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='usuarios.usuario')),
            ],
        ),
    ]
