# Generated by Django 4.2.11 on 2026-09-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='session_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
