# Generated by Django 4.2.11 on 2026-09-12 00:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(choices=[('tarea', 'tarea'), ('proyecto', 'proyecto')], max_length=20)),
                ('objeto_id', models.CharField(max_length=50)),
                ('permiso', models.CharField(choices=[('ver', 'ver'), ('editar', 'editar'), ('administrar', 'administrar')], default='ver', max_length=20)),
                ('fecha_compartida', models.DateTimeField(default=django.utils.timezone.now)),
                ('compartido_con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparticiones_recibidas', to='usuarios.usuario')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparticiones_creadas', to='usuarios.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comparticion',
            constraint=models.UniqueConstraint(fields=('compartido_con', 'tipo_objeto', 'objeto_id'), name='unica_comparticion_por_objeto'),
        ),
    ]
