# Generated by Django 4.2.11 on 2026-09-17 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_anadir_session_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestablecimientoContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restablecimientos', to='usuarios.usuario')),
            ],
        ),
    ]
