# Generated by Django 4.2.11 on 2026-09-11 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodoMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, default='#00E5FF', max_length=7)),
                ('posicion_x', models.FloatField(default=0.0)),
                ('posicion_y', models.FloatField(default=0.0)),
                ('convertido_en_tarea', models.BooleanField(default=False)),
                ('id_tarea_generada', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos_mapa', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ConexionNodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_destino', to='mapa_mental.nodomapa')),
                ('nodo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_origen', to='mapa_mental.nodomapa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_nodo', to='usuarios.usuario')),
            ],
        ),
    ]
