# Generated by Django 4.2.11 on 2026-09-11 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, default='', max_length=2000)),
                ('estado', models.CharField(choices=[('por_hacer', 'por_hacer'), ('en_progreso', 'en_progreso'), ('completado', 'completado')], default='por_hacer', max_length=20)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=50)),
                ('color_etiqueta', models.CharField(blank=True, default='#00E5FF', max_length=7)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('origen_nodo', models.CharField(blank=True, default='', max_length=50)),
                ('proyecto', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='usuarios.usuario')),
            ],
        ),
    ]
